In [44]:
import numpy as np

print(np.__version__)

Z = np.zeros(10, dtype=np.int32)
print(Z)



2.3.1
[0 0 0 0 0 0 0 0 0 0]


In [45]:
Z = np.arange(10,50)
print(Z)
Z = Z[10::-1]
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[20 19 18 17 16 15 14 13 12 11 10]


In [46]:
#### 9. Create a 3x3 matrix with values ranging from 0 to 8
Z = np.arange(0,9,dtype=np.int8).reshape(3,3)
Z

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]], dtype=int8)

In [47]:
#### 10. Find indices of non-zero elements from [1,2,0,0,4,0]
nz = np.nonzero([1,2,0,0,4,0])
print(nz[0])

[0 1 4]


In [48]:
A = np.eye(3)
A

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [49]:
Z = np.random.random((3,3,3))
X =np.random.randint(1, 10, size=(3, 3, 3))
X

array([[[8, 9, 8],
        [2, 8, 4],
        [6, 5, 7]],

       [[8, 7, 5],
        [6, 5, 4],
        [7, 3, 9]],

       [[1, 3, 9],
        [7, 7, 6],
        [9, 3, 6]]], dtype=int32)

In [50]:
Z = np.random.randint(1,10, size=(10,10))
print(Z)
print("\n")
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)
print("\n")
S = np.min(Z)
print(S)

[[7 4 3 3 4 4 1 2 6 4]
 [9 7 2 1 1 6 3 9 2 5]
 [9 6 2 8 6 8 9 1 6 4]
 [5 5 9 8 6 3 8 5 3 8]
 [1 1 7 8 7 7 3 3 4 8]
 [2 2 5 9 2 3 9 2 6 2]
 [9 1 5 1 8 4 4 4 3 3]
 [3 7 9 2 7 6 3 8 4 9]
 [6 9 9 6 9 1 6 7 4 2]
 [3 3 1 3 9 3 9 1 7 3]]


1 9


1


In [51]:
Z = np.random.randint(1,10, size=(1,10))
print(Z)
m = Z.mean()
print(m)


[[6 1 4 9 4 2 7 6 2 4]]
4.5


In [52]:
Z = np.ones((10,10),dtype = np.int32)
Z[1:-1,1:-1] = 0
print(Z)

[[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]


In [55]:
Z = np.ones((5,5),dtype=np.int32)
Z = np.pad(Z,pad_width=1,mode='constant',constant_values=0)
print(Z)


[[0 0 0 0 0 0 0]
 [0 1 1 1 1 1 0]
 [0 1 1 1 1 1 0]
 [0 1 1 1 1 1 0]
 [0 1 1 1 1 1 0]
 [0 1 1 1 1 1 0]
 [0 0 0 0 0 0 0]]


In [56]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])

True

In [1]:
import numpy as np
# Data matrix
matrix_A = np.array([[1, 0, 0, 3, 1], [3, 6, 6, 2, 9], [4, 5, 3, 8, 0]])
# Covariance matrix calculation
cov_matrix = np.cov(matrix_A)
print("Covariance matrix of matrix_A:\n", cov_matrix)

Covariance matrix of matrix_A:
 [[ 1.5 -2.   2. ]
 [-2.   7.7 -7. ]
 [ 2.  -7.   8.5]]


In [2]:
Z = np.array([[2, 4, 6], [8, 10, 12], [14, 16, 18]])

In [4]:
print(np.mean(Z))
print(np.median(Z))

10.0
10.0


In [5]:
Z = np.array([1,3,5,7,9,11,13,15,17,19])
print(np.percentile(Z,75))

14.5


In [6]:
Z = np.array([1,3,5,7,9,11,13,15,17,19])
print(np.percentile(Z,25))

5.5
