In [44]:
import numpy as np

print(np.__version__)

Z = np.zeros(10, dtype=np.int32)
print(Z)



2.3.1
[0 0 0 0 0 0 0 0 0 0]


In [45]:
Z = np.arange(10,50)
print(Z)
Z = Z[10::-1]
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[20 19 18 17 16 15 14 13 12 11 10]


In [46]:
#### 9. Create a 3x3 matrix with values ranging from 0 to 8
Z = np.arange(0,9,dtype=np.int8).reshape(3,3)
Z

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]], dtype=int8)

In [47]:
#### 10. Find indices of non-zero elements from [1,2,0,0,4,0]
nz = np.nonzero([1,2,0,0,4,0])
print(nz[0])

[0 1 4]


In [48]:
A = np.eye(3)
A

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [49]:
Z = np.random.random((3,3,3))
X =np.random.randint(1, 10, size=(3, 3, 3))
X

array([[[8, 9, 8],
        [2, 8, 4],
        [6, 5, 7]],

       [[8, 7, 5],
        [6, 5, 4],
        [7, 3, 9]],

       [[1, 3, 9],
        [7, 7, 6],
        [9, 3, 6]]], dtype=int32)

In [50]:
Z = np.random.randint(1,10, size=(10,10))
print(Z)
print("\n")
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)
print("\n")
S = np.min(Z)
print(S)

[[7 4 3 3 4 4 1 2 6 4]
 [9 7 2 1 1 6 3 9 2 5]
 [9 6 2 8 6 8 9 1 6 4]
 [5 5 9 8 6 3 8 5 3 8]
 [1 1 7 8 7 7 3 3 4 8]
 [2 2 5 9 2 3 9 2 6 2]
 [9 1 5 1 8 4 4 4 3 3]
 [3 7 9 2 7 6 3 8 4 9]
 [6 9 9 6 9 1 6 7 4 2]
 [3 3 1 3 9 3 9 1 7 3]]


1 9


1


In [51]:
Z = np.random.randint(1,10, size=(1,10))
print(Z)
m = Z.mean()
print(m)


[[6 1 4 9 4 2 7 6 2 4]]
4.5


In [52]:
Z = np.ones((10,10),dtype = np.int32)
Z[1:-1,1:-1] = 0
print(Z)

[[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]


In [55]:
Z = np.ones((5,5),dtype=np.int32)
Z = np.pad(Z,pad_width=1,mode='constant',constant_values=0)
print(Z)


[[0 0 0 0 0 0 0]
 [0 1 1 1 1 1 0]
 [0 1 1 1 1 1 0]
 [0 1 1 1 1 1 0]
 [0 1 1 1 1 1 0]
 [0 1 1 1 1 1 0]
 [0 0 0 0 0 0 0]]


In [56]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])

True

In [1]:
import numpy as np
# Data matrix
matrix_A = np.array([[1, 0, 0, 3, 1], [3, 6, 6, 2, 9], [4, 5, 3, 8, 0]])
# Covariance matrix calculation
cov_matrix = np.cov(matrix_A)
print("Covariance matrix of matrix_A:\n", cov_matrix)

Covariance matrix of matrix_A:
 [[ 1.5 -2.   2. ]
 [-2.   7.7 -7. ]
 [ 2.  -7.   8.5]]


In [2]:
Z = np.array([[2, 4, 6], [8, 10, 12], [14, 16, 18]])

In [4]:
print(np.mean(Z))
print(np.median(Z))

10.0
10.0


In [5]:
Z = np.array([1,3,5,7,9,11,13,15,17,19])
print(np.percentile(Z,75))

14.5


In [6]:
Z = np.array([1,3,5,7,9,11,13,15,17,19])
print(np.percentile(Z,25))

5.5


In [7]:
import pandas as pd
fruits = ["apples", "oranges", "cherries", "pears"]
fruits_ro = ["mere", "portocale", "cirese", "pere"]
S = pd.Series([20, 33, 52, 10], index=fruits)
S2 = pd.Series([17, 13, 311, 32], index=fruits_ro)
print(S)
print(S2)
print(S + S2)

apples      20
oranges     33
cherries    52
pears       10
dtype: int64
mere          17
portocale     13
cirese       311
pere          32
dtype: int64
apples      NaN
cherries    NaN
cirese      NaN
mere        NaN
oranges     NaN
pears       NaN
pere        NaN
portocale   NaN
dtype: float64


In [3]:
""" 
Instructions :

Create a list of products, 'Apple', 'Banana', 'Carrot', 'Daikon'.
Convert the list into a pandas Series using the pd.Series() function.
Print out the new Series to see the values.
Create a Series with prices of the products, [2, 1, 3, 4]
Print out the new Series to see the values.
Add the two Series together and print out the result.
Create a DataFrame using a dictionary of lists, where the keys are 'Product' and 'Price' and the values are the two Series you created.
Print out the DataFrame to see the values.
Create a DataFrame using a list of dictionaries, where each dictionary represents a row in the DataFrame with keys 'Product' and 'Price' and values from the two Series you created.
Print out the DataFrame to see the values. Make sure to import pandas library before doing the exercises. 
"""
import pandas as pd
list_3 = ["apple","banana","carrot","daikon"]
list_3_series = pd.Series(list_3)
print(list_3_series)

0     apple
1    banana
2    carrot
3    daikon
dtype: object


In [6]:
prices_series = pd.Series([2, 1, 3, 4])
prices_series

0    2
1    1
2    3
3    4
dtype: int64

In [11]:
data = {"ProductName": list_3_series, "ProductPrice": prices_series}
df = pd.DataFrame(data)
df

ProductName  ProductPrice
0       apple             2
1      banana             1
2      carrot             3
3      daikon             4

In [13]:
data = [
    {"product":"apple","price":"2"},
    {"product":"banana","price":"1"},
    {"product":"carrot","price":"1"},
    {"product":"daikon","price":"4"}
]

df = pd.DataFrame(data)
df

product price
0   apple     2
1  banana     1
2  carrot     1
3  daikon     4

In [2]:
import pandas as pd

data = {
        'Name': ['John', 'Mary', 'Bob', 'Sarah', 'Tom', 'Lisa'],
        'Department': ['IT', 'Marketing', 'Sales', 'IT', 'Finance', 'Marketing'],
        'Age': [30, 40, 25, 35, 45, 28],
        'Gender': ['Male', 'Female', 'Male', 'Female', 'Male', 'Female'],
        'Salary': [50000, 60000, 45000, 55000, 70000, 55000],
        'Experience': [3, 7, 2, 5, 10, 4]
        }

employee_df = pd.DataFrame(data)
print(employee_df)


    Name Department  Age  Gender  Salary  Experience
0   John         IT   30    Male   50000           3
1   Mary  Marketing   40  Female   60000           7
2    Bob      Sales   25    Male   45000           2
3  Sarah         IT   35  Female   55000           5
4    Tom    Finance   45    Male   70000          10
5   Lisa  Marketing   28  Female   55000           4


In [ ]:
#Select the first 3 rows of the dataframe
selected_rows = employee_df.iloc[:3,:]


#Select all rows where the Department is "Marketing"
selected_Marketing = employee_df.loc[employee_df["Department"]== "Marketing"]
print(selected_Marketing)

   Name Department  Age  Gender  Salary  Experience
1  Mary  Marketing   40  Female   60000           7
5  Lisa  Marketing   28  Female   55000           4


In [3]:
#select the Age and Gender columns for the first 4 rows of the dataframe.
selected_4rows = employee_df.iloc[0:4,[2,3]]
print(selected_4rows)

   Age  Gender
0   30    Male
1   40  Female
2   25    Male
3   35  Female


In [4]:
#select the Salary and Experience columns for all rows where the Gender is "Male".
selected_male = employee_df.loc[employee_df["Gender"]== "Male", ["Salary","Experience"]]
selected_male

Salary  Experience
0   50000           3
2   45000           2
4   70000          10